export const colors = {
  background: "#FFFFFF",
  screenBackground: "transparent",
  surface: "#E2F2F2",
  surfaceSoft: "#A5D3D3",
  border: "#4F9B9B",
  textPrimary: "#0F4E4E",
  textSecondary: "#166A6A",
  textMuted: "#2B7F7F",
  accent: "#2B7F7F",
  warmAccent: "#E88C4A",
  warmAccentDark: "#D97832",
  warmAccentSoft: "#F2A86F",
  warmSurface: "#FBE3D1",
  disabled: "#A5D3D3",
};
